### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AnthonyMastrean**
Change the RSS link to a cute lil badge thingie.

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
Thanks. This is a good idea for a change, but I'm going to see if I can find another source to pull the svg from, as I always try to keep any third-party resources my sites pull from to a minimum, and do so from sources I have more confidence in.

**Comment by AnthonyMastrean** [comment]
The source is MIT licensed, not sure if that means you can just copy the SVG into your repo.

https://github.com/aleen42/badges/blob/master/LICENSE

**Comment by 0xdabbad00** [comment]
I grabbed the icon from https://www.mozilla.org/en-US/foundation/feed-icon-guidelines/ and added it in #20 

I'm sorry I'm not very good at merging PRs in order to get you into the commits for this idea.

**Comment by AnthonyMastrean** [comment]
No problem!

**Pull request closed without merging**
